import Head from "next/head";
import { useSession } from "next-auth/react"; // Import useSession hook from next-auth/react
import Hero from "@/components/Hero/Hero";
import Products from "@/components/products/Products";
import NewArrival from "@/components/NewArrival/NewArrival";
import Service from "@/components/services/Service";
import style from "./Home.module.css";
import DatabseProducts from "@/components/database-products/DatabaseProducts";

export default function Home() {
  const { data: session, status } = useSession(); 
  // If session is not loaded yet, show loading state or null
  if (status === "loading") {
    return <div>Loading...</div>;
  }

  // If no session exists, redirect to login page
  if (!session) {
    if (typeof window !== "undefined") {
      window.location.href = "/login";
    }
    return null; 
  }


  return (
    <>
      <Head>
        <title>Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Hero />
      <DatabseProducts />
      <Products />

      <NewArrival />
      <div className={style.service_container}>
        <Service
          imgPath="/images/Services-1.svg"
          title="FREE AND FAST DELIVERY"
          description="Free delivery for all orders over $140"
        />
        <Service
          imgPath="/images/Services-2.svg"
          title="24/7 CUSTOMER SERVICE"
          description="Friendly 24/7 customer support"
        />
        <Service
          imgPath="/images/Services-3.svg"
          title="MONEY BACK GUARANTEE"
          description="We return money within 30 days"
        />
      </div>
    </>
  );
}
