import Head from "next/head";

import Hero from "@/components/Hero/Hero";
import Products from "@/components/products/Products"

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Hero/>
      <Products/>
    </>
  )
}
